version: "3"
services:
  front:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - API_BASE_URL=http://backend:8000/api
    networks:
      - myapp-network
  # MEMO: URLによって振り分けるコンテナを決めるためにNginxが必要
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - myapp-network
# MEMO: バックエンドコンテナとの通信をするためにnetworkが必要
networks:
  myapp-network:
    external: true
